name: Laporkan Bug
description: Laporkan bug mengenai situs.
title: '[BUG] example.com'
labels: 
  - bug
  - sites
assignees: 
  - ryukora
body:
  - type: markdown
    attributes:
      value: |
        Terima kasih telah melaporkan adanya masalah!
        Pastikan website yang akan dilaporkan tidak terdapat duplikat issue.
  - type: input
    id: deskripsi
    attributes:
      label: Deskripsi mengenai bug
      description: Deskripsi jelas dan ringkas tentang apa yang terjadi.
      placeholder: Masalah
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: Jika ada, tambahkan screenshot untuk membantu menjelaskan mengenai bug.
      placeholder: Screenshot
  - type: input
    id: os
    attributes:
      label: Sistem Operasi (OS)
      description: Masukkan sistem operasi yang Anda gunakan.
      placeholder: Windows 11, macOS, Debian Linux
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: Masukkan browser yang Anda gunakan.
      placeholder: Chrome, Firefox, Edge
    validations:
      required: true
